#!/usr/bin/env bash
# Write an .env for a local sink from examples/docker-compose.yml and run a
# small metadata-only scrape. Development helper — throwaway credentials only.
#
#   ./examples/quickstart.sh postgres
#   ./examples/quickstart.sh sqlite
#   ./examples/quickstart.sh mysql
set -euo pipefail

SINK="${1:-}"
if [[ -z "$SINK" ]]; then
  echo "usage: $0 <sink>   (postgres|mysql|mariadb|sqlite|duckdb|mongodb|clickhouse|neo4j|surrealdb)" >&2
  exit 2
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

case "$SINK" in
  postgres)   EXTRA=postgres;   ENV_LINES=$'POSTGRES_DSN=postgresql://hkex:hkex@localhost:5432/hkex' ;;
  mysql)      EXTRA=mysql;      ENV_LINES=$'MYSQL_HOST=127.0.0.1\nMYSQL_PORT=3306\nMYSQL_DATABASE=hkex\nMYSQL_USER=hkex\nMYSQL_PASSWORD=hkex' ;;
  mariadb)    EXTRA=mysql;      ENV_LINES=$'MARIADB_HOST=127.0.0.1\nMARIADB_PORT=3307\nMARIADB_DATABASE=hkex\nMARIADB_USER=hkex\nMARIADB_PASSWORD=hkex' ;;
  sqlite)     EXTRA="";         ENV_LINES=$'SQLITE_PATH=hkex.db' ;;
  duckdb)     EXTRA=duckdb;     ENV_LINES=$'DUCKDB_PATH=hkex.duckdb' ;;
  mongodb)    EXTRA=mongodb;    ENV_LINES=$'MONGODB_URI=mongodb://localhost:27017\nMONGODB_DATABASE=hkex' ;;
  clickhouse) EXTRA=clickhouse; ENV_LINES=$'CLICKHOUSE_HOST=localhost\nCLICKHOUSE_PORT=8123\nCLICKHOUSE_DATABASE=hkex\nCLICKHOUSE_USER=hkex\nCLICKHOUSE_PASSWORD=hkex' ;;
  neo4j)      EXTRA=neo4j;      ENV_LINES=$'NEO4J_URI=bolt://localhost:7687\nNEO4J_USER=neo4j\nNEO4J_PASSWORD=hkexpassword' ;;
  surrealdb)  EXTRA="";         ENV_LINES=$'SURREAL_ENDPOINT=http://localhost:8000\nSURREAL_PASSWORD=root' ;;
  *) echo "unknown sink: $SINK" >&2; exit 2 ;;
esac

{
  echo "# Generated by examples/quickstart.sh — development only."
  echo "DATABASE_TARGET=$SINK"
  printf '%s\n' "$ENV_LINES"
} > .env

echo "Wrote .env for '$SINK'."
if [[ -n "$EXTRA" ]]; then
  echo "Installing driver: pip install \".[$EXTRA]\""
  pip install ".[$EXTRA]"
fi

echo "Running: hkex-scraper --metadata-only --limit 50"
hkex-scraper --metadata-only --limit 50
